package com.riviem.findmyphoneclap.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFB5C4FF)
val md_theme_dark_onPrimary = Color(0xFF052978)
val md_theme_dark_primaryContainer = Color(0xFF264190)
val md_theme_dark_onPrimaryContainer = Color(0xFFDCE1FF)
val md_theme_dark_secondary = Color(0xFFC1C5DD)
val md_theme_dark_onSecondary = Color(0xFF2B3042)
val md_theme_dark_secondaryContainer = Color(0xFF414659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE1F9)
val md_theme_dark_tertiary = Color(0xFFE3BADB)
val md_theme_dark_onTertiary = Color(0xFF432740)
val md_theme_dark_tertiaryContainer = Color(0xFF5B3D57)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C6D0)
val md_theme_dark_outline = Color(0xFF8F909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E6)
val md_theme_dark_inversePrimary = Color(0xFF415AA9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB5C4FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)

val ActivateButtonColor = Color(0xFF32A49E)
val BackgroundTopColor = Color(0xFF192C3C)
val BackgroundBottomColor = Color(0xFF1F2236)


val seed = Color(0xFF1B2136)
